### ISSUE TITLE
Which base62 algo does this use?

### ISSUE THREAD

**Issue by coolaj86** [Sija/base62.cr#2]
My understanding is that there is no formal spec for base62, but that the ["glowfall"](https://github.com/glowfall/base62) implementation (despite its lack of stars) has become the _de facto_ implementation (used the most across the most repos).

Does this follow that spec? Or a different one? Or create a new one?

**Comment by Sija** [comment]
I don't even remember myself, sorry 😅  It might follow none as far as I'm concerned ;)
